#' Write out a graphic to a png file
#'
#' Write a ggplot object to a .png file. Defaults to 300dpi resolution on
#' "letter" sized paper in portrait orientation with standard margins.
#' Automatically adds a ".png" suffix to the provided filename.
#' @param object to plot (usually generated by ggplot)
#' @param fn file name (without .png suffix)
#' @param x horizontal dimensions of default graphic (defaults to 6.5)
#' @param y vertical dimensinos of default graphic (defaults to 4.875)
#' @param uni units of measurement for the dimension (defaults to "in")
#' @param rez resolution of output graphic (pixels per unit)
#' @seealso \code{\link{png}}, \code{\link{pdf}}, \code{\link{jpeg}},
#' \code{\link{dev.off}}
#' @export
ggpng <- function(P, fn, x=6.5, y=6.5 * 3/4, uni="in", rez=300,
                  gdir=NULL) {
    if (is.null(gdir)) {
        gdir <- graphics
    }
    fname <- paste0(graphics, fn, ".png")
    png(fname, x, y, units=uni, res=rez)
    print(P)
    dev.off()
}

#' display the size of an R object in appropirate units
#'
#' Display the size of an R object in scale-appropriate units. Sometimes
#' useful for deciding if a particular object should be re-generated as
#' needed or saved and loaded on repeat analysis.
#' @param x an object in the environment
#' @export
sizeof <- function(x) {
    print(object.size(x), units="auto")
}

#' Turn dashes to zeros
#'
#' Take a character vector of numbers where dashes indicate negligible
#' values, and return a numeric vector where dashes have been set to 0.
#' @param x a character vector to be cleaned
#' @export
dash20s <- function(x) {
  x[x=="-"] <- "0"
  return(as.numeric(x))
}

#' Possibly output a timestamp
#'
#' If the value passed is greater than the threshold, call the timestamp()
#' function.
#' @param noisy a flag, set to differing values depending upon how many
#' timestamps you want
#' @param trigger if the flag is greater than this value call
#' timestamp(). Defautls to zero.
#' @export
ntimestamp <- function(noisy, trigger=0) {
  if (noisy > trigger)
    timestamp()
}
#' Possibly output a status message
#'
#' If the value passed is greater than the threshold, pass the remaining
#' arguments to cat() to be sent to the output stream. Useful for tracking
#' progress of a long script with tuneable feedback.
#' @param noisy a flag, set to differing values depending upon how many
#' output you want
#' @param trigger if the flag is greater than this value call
#' cat(). Defautls to zero.
#' @export
ncat <- function(noisy, trigger=0, ...) {
  if (noisy > trigger)
    cat(..., sep="")
}
